### ISSUE TITLE
AOT compiling error

### ISSUE THREAD

**Issue by sterlingwarrior** [cornflourblue/jw-angular-pagination#2]
When I try to compile with --aot flag I get the following error.  

ERROR in Error: Unexpected value 'JwPaginationComponent in /Users/codev/workspace/cumulus/node_modules/jw-angular-pagination/lib/jw-pagination.component.d.ts' declared by the module 'AppModule in /Users/codev/workspace/cumulus/src/app/app.module.ts'. Please add a @Pipe/@Directive/@Component annotation.
    at syntaxError (/Users/codev/workspace/cumulus/node_modules/@angular/compiler/bundles/compiler.umd.js:1729:34)
    at /Users/codev/workspace/cumulus/node_modules/@angular/compiler/bundles/compiler.umd.js:15481:40
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (/Users/codev/workspace/cumulus/node_modules/@angular/compiler/bundles/compiler.umd.js:15463:54)
    at addNgModule (/Users/codev/workspace/cumulus/node_modules/@angular/compiler/bundles/compiler.umd.js:24268:58)
    at /Users/codev/workspace/cumulus/node_modules/@angular/compiler/bundles/compiler.umd.js:24279:14
    at Array.forEach (native)
    at _createNgModules (/Users/codev/workspace/cumulus/node_modules/@angular/compiler/bundles/compiler.umd.js:24278:26)
    at analyzeNgModules (/Users/codev/workspace/cumulus/node_modules/@angular/compiler/bundles/compiler.umd.js:24153:14)
    at analyzeAndValidateNgModules (/Users/codev/workspace/cumulus/node_modules/@angular/compiler/bundles/compiler.umd.js:24163:35)
    at AotCompiler.analyzeModulesAsync (/Users/codev/workspace/cumulus/node_modules/@angular/compiler/bundles/compiler.umd.js:23797:46)
    at CodeGenerator.codegen (/Users/codev/workspace/cumulus/node_modules/@angular/compiler-cli/src/codegen.js:32:14)
    at Function.NgTools_InternalApi_NG_2.codeGen (/Users/codev/workspace/cumulus/node_modules/@angular/compiler-cli/src/ngtools_api.js:73:30)
    at _donePromise.Promise.resolve.then (/Users/codev/workspace/cumulus/node_modules/@ngtools/webpack/src/plugin.js:428:58)

**Comment by cornflourblue** [comment]
Thanks @sterlingwarrior, this should be fixed now with version 1.0.5

I just needed to generate and publish the .metadata.json file to npm
